---
- hosts: all
  gather_facts: no
  tasks:
  - include_vars: "vars/vault.yml"
  - include_vars: "vars/main.yml"
  - name: check for root access
    ## This check uses local_action, because ssh as root, if it doesn't work,
    ## causes UNREACHABLE, which is fatal to ansible
    local_action: "command ssh -q -o BatchMode=yes -o ConnectTimeout=3 root@{{ inventory_hostname }} 'echo ok'"
    changed_when: false
    register: root_accessible
    ignore_errors: yes
  - name: lock-out root
    include_role:
      name: lock-root
    vars:
      # have the role use the root login to set up the devops_ssh_user
      ansible_user: root
      admin_user: "{{ devops_ssh_user }}"
      ansible_ssh_port: 22
    when: root_accessible | success
  - name: setup with ansible_user
    vars:
      ansible_user: "{{ devops_ssh_user }}"
      ansible_ssh_port: "{{ devops_ssh_port }}"
    block:
      - name: do gather_facts
        setup:
      - name: set up security
        become: true
        include_role:
          name: security-setup
      - name: install packages
        become: true
        include_role:
          name: install-packages
      - name: install ruby
        include_role:
          name: ruby-env
      - name: install nginx
        become: yes
        include_role:
          name: nginx
      - name: install passenger
        become: yes
        include_role:
          name: passenger
      - name: install mysql
        become: yes
        include_role:
          name: mysql
      - include_tasks: "ssl-cert.yml"
        become: yes
