---
# all of these commands require sudo
# caller must set `become: true`

- name: Install essential packages
  apt:
    name:
      - git-core
      - build-essential
      - openssl
      - curl
      - libssl-dev
      - libyaml-dev
      - libxml2-dev
      - libxslt-dev
      - autoconf
      - automake
      - libtool
      - bison
      - libreadline-dev
      - zlib1g-dev
      - imagemagick

